/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Guay0 (https://sketchfab.com/Guay0)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/leather-wooden-chest-3d-scan-quixel-megascans-36731e079ff044febf94c0fe9ec1d063
title: Leather Wooden Chest - 3D scan Quixel Megascans
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGraph } from '@react-three/fiber'

export function Model(props) {
  const { nodes, materials} = useGLTF('/scene.gltf')
  

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Leather_Wooden_vigiaeoga} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
